package de.stylabs.lynx.parser;

public enum ASTType {
    PROGRAM,
    FUNCTION_DECLARATION,
    FUNCTION_CALL,
    VARIABLE_DECLARATION,
    VARIABLE_ASSIGNMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    RETURN_STATEMENT,
    BINARY_EXPRESSION,
    UNARY_EXPRESSION,
    LITERAL,
    IDENTIFIER,
    BLOCK_STATEMENT,
    EXPRESSION_STATEMENT,
    CLASS_DECLARATION,
    VARIABLE_VALUE,
    PARAMETER,
    FUNCTION_RETURN_TYPE,
}
