package de.stylabs.parser;

public enum ASTTypes {
    PROGRAM,
    FUNCTION,
    FUNCTION_CALL,
    VARIABLE_DECLARATION,
    VARIABLE_ASSIGNMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    RETURN_STATEMENT,
    BINARY_EXPRESSION,
    UNARY_EXPRESSION,
    LITERAL,
    IDENTIFIER,
    BLOCK_STATEMENT,
    EXPRESSION_STATEMENT
}
